spring.application.name=ems-api
server.servlet.context-path=/ems/api

server.port=8081

# Shared Session Configuration
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=${SESSION_COOKIE_SECURE:false}
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.path=/
spring.session.jdbc.initialize-schema=never
spring.session.jdbc.table-name=SPRING_SESSION

# Logging Configuration
debug=${DEBUG:false}
logging.level.org.springframework=${SPRING_LOG_LEVEL:info}
logging.level.com.via.ems=${EMS_LOG_LEVEL:info}
logging.file.path=logs
logging.file.name=logs/ems-api.log

### DATABASE CREDENTIALS ###
spring.datasource.url=jdbc:mysql://localhost:3306/ems_db
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

### Spring JPA Configuration ###
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

#### Swagger Configuration ###
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.csrf.enabled=true
springdoc.swagger-ui.csrf.cookie-name=XSRF-TOKEN
springdoc.swagger-ui.csrf.header-name=X-XSRF-TOKEN
